# Generated by Django 2.2.6 on 2020-04-17 12:22

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', core.models.CICharField(error_messages={'unique': 'Client is already existed.'}, max_length=32, unique=True)),
            ],
        ),
    ]
