# Generated by Django 2.2.6 on 2020-04-17 18:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20200417_1901'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectinfo',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.ClientInfo'),
        ),
    ]
