# Generated by Django 2.2.6 on 2020-04-20 11:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20200418_0012'),
    ]

    operations = [
        migrations.AddField(
            model_name='csrtemplate',
            name='client',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='core.ClientInfo'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='protocoladmin',
            name='client',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='core.ClientInfo'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='saradmin',
            name='client',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='core.ClientInfo'),
            preserve_default=False,
        ),
    ]
