# Generated by Django 2.2.6 on 2020-04-20 12:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20200420_1725'),
    ]

    operations = [
        migrations.AddField(
            model_name='globalmappingtable',
            name='client',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='core.ClientInfo'),
            preserve_default=False,
        ),
    ]
