# Generated by Django 2.2.6 on 2020-05-06 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_library'),
    ]

    operations = [
        migrations.AlterField(
            model_name='csrtemplate',
            name='version_no',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
