# Generated by Django 2.2.6 on 2020-05-06 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20200506_1439'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anotherfileuploaduser',
            name='version_no',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='csrtemplateuser',
            name='version_no',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='protocoladmin',
            name='version_no',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='protocolfileupload',
            name='version_no',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='saradmin',
            name='version_no',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='sarfileupload',
            name='version_no',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
