# Generated by Django 2.2.6 on 2020-05-06 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20200506_1456'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generated_reports',
            name='version_no',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
